plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.ksp)
}

android {
    namespace 'com.example.matchmate'
    compileSdk 37
    buildFeatures {
        viewBinding true
    }

    defaultConfig {
        applicationId "com.example.matchmate"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'androidx.recyclerview:recyclerview:1.4.0'

    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.7'

    implementation 'androidx.room:room-runtime:2.8.4'
    implementation 'androidx.room:room-ktx:2.8.4'
    ksp 'androidx.room:room-compiler:2.8.4'

    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.11.0'

    implementation 'com.github.bumptech.glide:glide:4.16.0'
    kapt 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    // Source - https://stackoverflow.com/a/60830396

    // For Activities
    implementation("androidx.activity:activity-ktx:1.9.1")

    // For Fragments (Add this if you are using viewModels() inside a Fragment)
    implementation("androidx.fragment:fragment-ktx:1.8.2")

}